# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glorfindel
email: mark.monteiro23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mark-monteiro.github.io/dnd-character" # the base hostname & protocol for your site

# Github Unmodifiable Settings
safe: true
lsi: false
source: .

# Github Defaults
highlighter: pygments
#github: [Repository metadata]

prose:
  rooturl: ''
  siteurl: 'http://mark-monteiro.github.io/dnd-character/'
  relativeLinks: 'mark-monteiro.github.io/dnd-character/links.jsonp'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /scripts
    - .*
  metadata:
    _spells:
      - name: "name"
        field:
          element: "text"

      - name: "prepared"
        field:
          element: "checkbox"
          value: false

      - name: "classes"
        field:
          element: "multiselect"
          options:
            - name: Druid
              value: druid
            - name: Cleric
              value: cleric

      - name: "type"
        field:
          element: "select"
          options:
            - name: Abjuration
              value: abjuration
            - name: Enchantment
              value: enchantment
            - name: Transmutation
              value: transmutation
            - name: Conjuration
              value: Conjuration
            - name: Divination
              value: divination

      - name: "ritual"
        field:
          element: "checkbox"
          value: false

      - name: "level"
        field:
          element: "number"

      - name: "time"
        field:
          element: "text"
          label: "Casting Time"

      - name: "range"
        field:
          element: "text"

      - name: "components"
        field:
          element: "text"

      - name: "material-components"
        field:
          element: "text"
          label: "Material Components"
          help: ex. "Additional meterial component required for the spell (i.e. a forked twig)"

      - name: "duration"
        field:
          element: "text"

collections:
  spells:
    output: true
  characters:
    output: true

defaults:
  # Spell Defaults
  -
    scope:
      path: ""
      type: spells
    values:
      layout: spell
      ritual: false
      time: "1 action"
  -
    scope:
      path: ""
      type: characters
    values:
      layout: character
