# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "D&D Character Viewer"
email: mark.monteiro23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Store all your D&D characters online! Save a bio and spell list for each of
  your characters. Also features a searchable and filterable list of all spells.
url: "https://dnd-characters.markmonteiro.info" # the base hostname & protocol for your site
github-username: "mark-monteiro"

# Github Unmodifiable Settings
safe: true
lsi: false
source: .

# Github Defaults
markdown:    kramdown
highlighter: rouge
#github: [Repository metadata]

prose:
  rooturl: ''
  siteurl: 'https://dnd-characters.markmonteiro.info/'
  relativeLinks: 'dnd-characters.markmonteiro.info/links.jsonp'
  media: 'media'
  ignore:
    - .gitignore
    - _config.yml
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - about.md
    - dnd-favicon.ico
    - feed.xml
    - index.html
    - links.jsonp
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /scripts
    - /json
  metadata:
    _spells:
      - name: "name"
        field:
          label: "Name"
          element: "text"

      - name: "classes"
        field:
          label: "Classes"
          element: "multiselect"
          options: "https://dnd-characters.markmonteiro.info/json/classes.jsonp?callback=classes"

      - name: "school"
        field:
          label: "School Of Magic"
          element: "select"
          options:
            - name: Abjuration
              value: Abjuration
            - name: Conjuration
              value: Conjuration
            - name: Divination
              value: Divination
            - name: Enchantment
              value: Enchantment
            - name: Evocation
              value: Evocation
            - name: Illusion
              value: Illusion
            - name: Necromancy
              value: Necromancyion
            - name: Transmutation
              value: Transmutation

      - name: "ritual"
        field:
          label: "Ritual"
          element: "checkbox"
          value: false

      - name: "level"
        field:
          label: "Level"
          element: "number"

      - name: "castingTime"
        field:
          label: "Casting Time"
          element: "text"

      - name: "range"
        field:
          label: "Range"
          element: "text"

      - name: "components"
        field:
          label: "Components"
          element: "text"
          help: "V(verbal), S(somatic) and/or M(material)"

      - name: "material"
        field:
          label: "Material Component(s)"
          element: "text"
          help: ex. "Additional meterial component required for the spell (i.e. a forked twig)"

      - name: "duration"
        field:
          label: "Duration"
          element: "text"

      - name: "concentration"
        field:
          label: "Concentration"
          element: "checkbox"
          help: check if this spell requires concentration

    _characters:
      - name: "spells"
        field:
          label: "Spells"
          element: "multiselect"
          options: "https://dnd-characters.markmonteiro.info/json/spells.jsonp?callback=spells"

collections:
  spells:
    output: true
  characters:
    output: true

defaults:
  # Spell Defaults
  -
    scope:
      path: ""
      type: spells
    values:
      layout: spell
      ritual: false
      time: "1 action"
  # Character defaults
  -
    scope:
      path: ""
      type: characters
    values:
      layout: character
