# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "D&D Character Viewer"
email: mark.monteiro23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dnd-character" # the subpath of your site, e.g. /blog
url: "http://mark-monteiro.github.io/dnd-character" # the base hostname & protocol for your site
github-username: "mark-monteiro"

# Github Unmodifiable Settings
safe: true
lsi: false
source: .

# Github Defaults
highlighter: pygments
#github: [Repository metadata]

prose:
  rooturl: ''
  siteurl: 'http://mark-monteiro.github.io/dnd-character/'
  relativeLinks: 'mark-monteiro.github.io/dnd-character/links.jsonp'
  media: 'media'
  ignore:
    - .gitignore
    - _config.yml
    - Gemfile
    - Gemfile.lock
    - about.md
    - dnd-favicon.ico
    - feed.xml
    - index.html
    - links.jsonp
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /scripts
    - /json
  metadata:
    _spells:
      - name: "name"
        field:
          label: "Name"
          element: "text"

      - name: "classes"
        field:
          label: "Classes"
          element: "multiselect"
          options:
            - name: Druid
              value: Druid
            - name: Cleric
              value: Cleric

      - name: "type"
        field:
          label: "Spell Type"
          element: "select"
          options:
            - name: Abjuration
              value: abjuration
            - name: Conjuration
              value: Conjuration
            - name: Divination
              value: divination
            - name: Enchantment
              value: enchantment
            - name: Evocation
              value: evocation
            - name: Illusion
              value: illusion
            - name: Necromancy
              value: transmutation
            - name: Transmutation
              value: transmutation

      - name: "ritual"
        field:
          label: "Ritual"
          element: "checkbox"
          value: false

      - name: "level"
        field:
          label: "Level"
          element: "number"

      - name: "time"
        field:
          label: "Casting Time"
          element: "text"

      - name: "range"
        field:
          label: "Range"
          element: "text"

      - name: "components"
        field:
          label: "Components"
          element: "text"

      - name: "material-components"
        field:
          label: "Material Components"
          element: "text"
          help: ex. "Additional meterial component required for the spell (i.e. a forked twig)"

      - name: "duration"
        field:
          label: "Duration"
          element: "text"

    _characters:
      - name: "spells"
        field:
          label: "Spells"
          element: "multiselect"
          options: "http://mark-monteiro.github.io/dnd-character/json/spells.jsonp?callback=spells"

collections:
  spells:
    output: true
  characters:
    output: true

defaults:
  # Spell Defaults
  -
    scope:
      path: ""
      type: spells
    values:
      layout: spell
      ritual: false
      time: "1 action"
  -
    scope:
      path: ""
      type: characters
    values:
      layout: character
